title: Nkosi Abram Mjoli's Portfolio 

author:
  name: "Nkosi Abram Mjoli"
  email: "mjolinkosi82@gmail.com"
  location: "Mangaung, Bloemfontein"
  social:
  linkedin: "https://www.linkedin.com/in/nkosi-mjoli-4a0106348?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
    github: "https://github.com/Mjoeman98/Mjoeman-portfolio" 

description: A professional portfolio showcasing the work and projects of Nkosi Abram Mjoli. 
  Focused on web development, HTML5, CSS3, JavaScript, and UI/UX design, 
  with a passion for creating clean, user-friendly web experiences.

social:
  linkedin: "https://www.linkedin.com/in/nkosi-mjoli-4a0106348?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
github: "https://github.com/Mjoeman98/Mjoeman-portfolio"

theme: jekyll-theme-minimal